remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
markdown: GFM
show_downloads: false
show_github: false
title: Random Bits
description: Landing page for random Bits of info organized as microsites.
